"""Embedded Chromium browser with automatic media detection."""

# PySide signals are generated by Shiboken and are invisible to pylint.
# pylint: disable=no-member

from __future__ import annotations

from datetime import datetime
import logging
import shutil
import subprocess
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from PySide6.QtCore import QObject, QStandardPaths, QTimer, QUrl, Signal, Slot
from PySide6.QtGui import QDesktopServices
from PySide6.QtWebEngineCore import QWebEnginePage, QWebEngineProfile, QWebEngineScript
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (
    QAbstractItemView,
    QFileDialog,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QMessageBox,
    QPushButton,
    QSplitter,
    QTableWidget,
    QTableWidgetItem,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

from app.browser.cookies import BrowserCookie, BrowserCookieJar
from app.browser.detector import MediaDetector
from app.browser.download_manager import BrowserDownloadManager
from app.browser.hls import parse_hls_playlist
from app.browser.http import BrowserHttpClient
from app.browser.interceptor import MediaRequestInterceptor
from app.browser.models import (
    BrowserDownloadSnapshot,
    BrowserMedia,
    BrowserMediaType,
    DownloadState,
)
from app.browser.player_capture import JWPLAYER_CAPTURE_SCRIPT
from app.config.settings import AppConfig
from app.core.exceptions import VideoDownloaderError
from app.utils.formatting import format_bytes

LOGGER = logging.getLogger("browser")
HOME_URL = "https://www.google.com"
MEDIA_SCAN_SCRIPT = """
(() => {
  const urls = new Set();
  document.querySelectorAll('video,audio,source').forEach(el => {
    if (el.currentSrc) urls.add(el.currentSrc);
    if (el.src) urls.add(el.src);
  });
  performance.getEntriesByType('resource').forEach(entry => urls.add(entry.name));
  return Array.from(urls).filter(url => /^https?:/i.test(url));
})()
"""


class _BrowserSignals(QObject):
    enriched = Signal(object)
    variants = Signal(object, object)
    download_changed = Signal(object)
    error = Signal(str)


class BrowserWebView(QWebEngineView):
    """Web view that redirects popups and target=_blank into browser tabs."""

    def __init__(self, owner: BrowserDownloaderTab) -> None:
        super().__init__()
        self.owner = owner

    def createWindow(  # noqa: N802  # pylint: disable=invalid-name
        self, _window_type: QWebEnginePage.WebWindowType
    ):
        """Create a new embedded browser tab for popup requests."""
        return self.owner.add_browser_tab(QUrl("about:blank"), switch=True)


class BrowserDownloaderTab(QWidget):
    """Browser UI, media table, and browser-download manager."""

    # Signal emitted when a file is saved: (title, saved_path, timestamp)
    file_saved = Signal(str, str, str)

    def __init__(self, config: AppConfig) -> None:
        super().__init__()
        self.config = config
        self.detector = MediaDetector()
        self.http = BrowserHttpClient()
        self.executor = ThreadPoolExecutor(max_workers=4, thread_name_prefix="media")
        self.signals = _BrowserSignals()
        self.signals.enriched.connect(self._add_media)
        self.signals.variants.connect(self._add_variants)
        self.signals.download_changed.connect(self._update_download)
        self.signals.error.connect(self._show_error)
        self.media_by_url: dict[str, BrowserMedia] = {}
        self.media_rows: dict[str, int] = {}
        self.download_rows: dict[str, int] = {}
        self.probed_candidates: set[str] = set()
        self.cookies = BrowserCookieJar()

        self.profile = QWebEngineProfile("BrowserDownloader", self)
        profile_root = Path(
            QStandardPaths.writableLocation(
                QStandardPaths.StandardLocation.AppDataLocation
            )
        )
        self.profile.setPersistentStoragePath(str(profile_root / "storage"))
        self.profile.setCachePath(str(profile_root / "cache"))
        self.profile.setDownloadPath(str(self.config.download_path))
        player_capture = QWebEngineScript()
        player_capture.setName("capture-player-media")
        player_capture.setInjectionPoint(
            QWebEngineScript.InjectionPoint.DocumentCreation
        )
        player_capture.setWorldId(QWebEngineScript.ScriptWorldId.MainWorld)
        player_capture.setRunsOnSubFrames(True)
        player_capture.setSourceCode(JWPLAYER_CAPTURE_SCRIPT)
        self.profile.scripts().insert(player_capture)
        self.interceptor = MediaRequestInterceptor(self.detector, self)
        self.interceptor.media_detected.connect(self._media_observed)
        self.interceptor.candidate_detected.connect(self._candidate_observed)
        self.interceptor.player_source_detected.connect(self._player_source_observed)
        self.profile.setUrlRequestInterceptor(self.interceptor)
        self.profile.cookieStore().cookieAdded.connect(self._cookie_added)

        self.manager = BrowserDownloadManager(
            config, listener=self.signals.download_changed.emit
        )
        self._build()
        self.add_browser_tab(QUrl(HOME_URL), switch=True)
        self.scan_timer = QTimer(self)
        self.scan_timer.timeout.connect(self._scan_current_page)
        self.scan_timer.start(4000)

    def _build(self) -> None:
        root = QVBoxLayout(self)
        root.setSpacing(8)
        root.setContentsMargins(8, 8, 8, 8)

        navigation = QHBoxLayout()
        navigation.setSpacing(4)
        for label, tooltip, callback in (
            ("◀", "Back", self._back),
            ("▶", "Forward", self._forward),
            ("↻", "Refresh", self._refresh),
            ("🏠", "Home", self._home),
        ):
            button = QPushButton(label)
            button.setToolTip(tooltip)
            button.setProperty("cssClass", "secondary")
            button.setFixedWidth(36)
            button.clicked.connect(callback)
            navigation.addWidget(button)
        self.address = QLineEdit()
        self.address.setPlaceholderText("Enter URL...")
        self.address.returnPressed.connect(self._go)
        navigation.addWidget(self.address, 1)
        go_button = QPushButton("Go")
        go_button.clicked.connect(self._go)
        navigation.addWidget(go_button)
        new_tab = QPushButton("+")
        new_tab.setToolTip("New browser tab")
        new_tab.setProperty("cssClass", "secondary")
        new_tab.setFixedWidth(36)
        new_tab.clicked.connect(lambda: self.add_browser_tab(QUrl(HOME_URL), True))
        navigation.addWidget(new_tab)
        root.addLayout(navigation)

        splitter = QSplitter()
        browser_panel = QWidget()
        browser_layout = QVBoxLayout(browser_panel)
        browser_layout.setContentsMargins(0, 0, 0, 0)
        self.browser_tabs = QTabWidget()
        self.browser_tabs.setTabsClosable(True)
        self.browser_tabs.setDocumentMode(True)
        self.browser_tabs.tabCloseRequested.connect(self._close_browser_tab)
        self.browser_tabs.currentChanged.connect(self._current_tab_changed)
        browser_layout.addWidget(self.browser_tabs)
        splitter.addWidget(browser_panel)

        results_panel = QWidget()
        results_layout = QVBoxLayout(results_panel)
        results_layout.setSpacing(8)
        results_layout.setContentsMargins(4, 4, 4, 4)

        media_heading = QLabel("🎯 Detected Media")
        media_heading.setProperty("cssClass", "heading")
        results_layout.addWidget(media_heading)

        self.media_table = QTableWidget(0, 6)
        self.media_table.setHorizontalHeaderLabels(
            ["Type", "Name", "Quality", "Size", "URL", "Action"]
        )
        self.media_table.setSelectionBehavior(
            QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.media_table.horizontalHeader().setSectionResizeMode(
            1, QHeaderView.ResizeMode.ResizeToContents
        )
        self.media_table.horizontalHeader().setSectionResizeMode(
            4, QHeaderView.ResizeMode.Stretch
        )
        self.media_table.verticalHeader().setDefaultSectionSize(28)
        self.media_table.verticalHeader().setVisible(False)
        results_layout.addWidget(self.media_table, 3)

        destination_row = QHBoxLayout()
        destination_row.setSpacing(6)
        dest_label = QLabel("💾 Save to")
        dest_label.setProperty("cssClass", "status")
        destination_row.addWidget(dest_label)
        self.destination = QLineEdit(str(self.config.download_path))
        destination_row.addWidget(self.destination, 1)
        browse = QPushButton("📂 Browse")
        browse.setProperty("cssClass", "secondary")
        browse.clicked.connect(self._browse)
        destination_row.addWidget(browse)
        results_layout.addLayout(destination_row)

        dm_heading = QLabel("📥 Downloads")
        dm_heading.setProperty("cssClass", "heading")
        results_layout.addWidget(dm_heading)

        self.download_table = QTableWidget(0, 7)
        self.download_table.setHorizontalHeaderLabels(
            ["Name", "Status", "Progress", "Speed", "ETA", "File", "Controls"]
        )
        self.download_table.horizontalHeader().setSectionResizeMode(
            0, QHeaderView.ResizeMode.Stretch
        )
        self.download_table.verticalHeader().setDefaultSectionSize(30)
        self.download_table.verticalHeader().setVisible(False)
        results_layout.addWidget(self.download_table, 2)
        splitter.addWidget(results_panel)
        splitter.setSizes([760, 520])
        root.addWidget(splitter, 1)

    def add_browser_tab(self, url: QUrl, switch: bool = True) -> BrowserWebView:
        """Create a browser tab using the shared persistent profile."""
        view = BrowserWebView(self)
        page = QWebEnginePage(self.profile, view)
        view.setPage(page)
        index = self.browser_tabs.addTab(view, "New tab")
        view.titleChanged.connect(
            lambda title, current=view: self._set_tab_title(current, title)
        )
        view.urlChanged.connect(
            lambda changed, current=view: self._url_changed(current, changed)
        )
        view.loadFinished.connect(lambda _ok, current=view: self._scan_view(current))
        if switch:
            self.browser_tabs.setCurrentIndex(index)
        view.setUrl(url)
        return view

    def _current_view(self) -> BrowserWebView | None:
        widget = self.browser_tabs.currentWidget()
        return widget if isinstance(widget, BrowserWebView) else None

    def _go(self) -> None:
        value = self.address.text().strip()
        if not value:
            return
        if "://" not in value:
            value = f"https://{value}"
        view = self._current_view()
        if view:
            LOGGER.info("navigation | url=%s", value)
            view.setUrl(QUrl(value))

    def _back(self) -> None:
        if view := self._current_view():
            view.back()

    def _forward(self) -> None:
        if view := self._current_view():
            view.forward()

    def _refresh(self) -> None:
        if view := self._current_view():
            view.reload()

    def _home(self) -> None:
        if view := self._current_view():
            view.setUrl(QUrl(HOME_URL))

    def _close_browser_tab(self, index: int) -> None:
        if self.browser_tabs.count() == 1:
            self.add_browser_tab(QUrl(HOME_URL), True)
        widget = self.browser_tabs.widget(index)
        self.browser_tabs.removeTab(index)
        widget.deleteLater()

    def _current_tab_changed(self, _index: int) -> None:
        if view := self._current_view():
            self.address.setText(view.url().toString())

    def _set_tab_title(self, view: BrowserWebView, title: str) -> None:
        index = self.browser_tabs.indexOf(view)
        if index >= 0:
            self.browser_tabs.setTabText(index, (title or "New tab")[:30])

    def _url_changed(self, view: BrowserWebView, url: QUrl) -> None:
        if view is self._current_view():
            self.address.setText(url.toString())
        LOGGER.info("navigation | url=%s", url.toString())

    def _scan_current_page(self) -> None:
        if view := self._current_view():
            self._scan_view(view)

    def _scan_view(self, view: BrowserWebView) -> None:
        source = view.url().toString()
        view.page().runJavaScript(
            MEDIA_SCAN_SCRIPT,
            lambda urls, page=source: self._javascript_media(urls, page),
        )

    def _javascript_media(self, urls: object, source_page: str) -> None:
        if not isinstance(urls, list):
            return
        for url in urls:
            if isinstance(url, str):
                media = self.detector.detect(
                    url,
                    source_page=source_page,
                    referer=source_page,
                    user_agent=self.profile.httpUserAgent(),
                )
                if media:
                    self._media_observed(media)
                else:
                    self._candidate_observed(url, source_page)

    @Slot(object)
    def _media_observed(self, media: BrowserMedia) -> None:
        if media.url in self.media_by_url:
            return
        enriched = media.model_copy(
            update={
                "user_agent": self.profile.httpUserAgent(),
                "cookies": self.cookies.header_for(media.url),
            }
        )
        self.media_by_url[media.url] = enriched
        self.executor.submit(self._enrich_media, enriched)

    @Slot(str, str)
    def _candidate_observed(self, url: str, source_page: str) -> None:
        if url in self.probed_candidates or len(self.probed_candidates) >= 500:
            return
        self.probed_candidates.add(url)
        self.executor.submit(self._probe_candidate, url, source_page)

    @Slot(str, str, str, str)
    def _player_source_observed(
        self, url: str, frame_url: str, media_type: str, label: str
    ) -> None:
        """Add a source explicitly configured by an embedded player."""
        hint = BrowserMediaType.HLS if media_type.lower() in {"hls", "m3u8"} else None
        media = self.detector.detect(
            url,
            source_page=frame_url,
            referer=frame_url,
            user_agent=self.profile.httpUserAgent(),
            media_type_hint=hint,
        )
        if media:
            if label:
                media = media.model_copy(update={"quality": label})
            self._media_observed(media)
        else:
            self._candidate_observed(url, frame_url)

    def _probe_candidate(self, url: str, source_page: str) -> None:
        try:
            metadata = self.http.probe(
                url,
                referer=source_page or None,
                user_agent=self.profile.httpUserAgent(),
                cookies=self.cookies.header_for(url),
            )
            media = self.detector.detect(
                metadata.final_url,
                mime_type=metadata.mime_type,
                size=metadata.size,
                source_page=source_page or None,
                referer=source_page or None,
                user_agent=self.profile.httpUserAgent(),
            )
            if media:
                media = media.model_copy(
                    update={"cookies": self.cookies.header_for(media.url)}
                )
                self.signals.enriched.emit(media)
                if media.media_type is BrowserMediaType.HLS:
                    content = self.http.get_text(
                        media.url,
                        referer=media.referer,
                        user_agent=media.user_agent,
                        cookies=media.cookies,
                    )
                    self.signals.variants.emit(
                        media, parse_hls_playlist(content, media.url)
                    )
        except VideoDownloaderError:
            pass

    def _enrich_media(self, media: BrowserMedia) -> None:
        try:
            metadata = self.http.probe(
                media.url,
                referer=media.referer,
                user_agent=media.user_agent,
                cookies=media.cookies,
            )
            enriched = self.detector.detect(
                metadata.final_url,
                mime_type=metadata.mime_type or media.mime_type,
                size=metadata.size,
                source_page=media.source_page,
                referer=media.referer,
                user_agent=media.user_agent,
                media_type_hint=media.media_type,
            )
            if enriched is None:
                enriched = media
            enriched = enriched.model_copy(update={"cookies": media.cookies})
            self.signals.enriched.emit(enriched)
            if enriched.media_type is BrowserMediaType.HLS:
                content = self.http.get_text(
                    enriched.url,
                    referer=enriched.referer,
                    user_agent=enriched.user_agent,
                    cookies=enriched.cookies,
                )
                variants = parse_hls_playlist(content, enriched.url)
                self.signals.variants.emit(enriched, variants)
        except VideoDownloaderError as exc:
            LOGGER.warning("media probe failed | url=%s | error=%s", media.url, exc)
            self.signals.enriched.emit(media)

    @Slot(object)
    def _add_media(self, media: BrowserMedia) -> None:
        if media.url in self.media_rows:
            return
        LOGGER.info("media detected | type=%s | url=%s", media.media_type, media.url)
        row = self.media_table.rowCount()
        self.media_table.insertRow(row)
        self.media_rows[media.url] = row
        self.media_by_url[media.url] = media
        values = (
            media.media_type.value,
            media.name,
            media.quality or "Source",
            format_bytes(media.size),
            media.url,
        )
        for column, value in enumerate(values):
            self.media_table.setItem(row, column, QTableWidgetItem(value))
        button = QPushButton("Download")
        button.clicked.connect(
            lambda _checked=False, item=media: self._start_download(item)
        )
        self.media_table.setCellWidget(row, 5, button)

    @Slot(object, object)
    def _add_variants(self, parent: BrowserMedia, variants: object) -> None:
        for variant in variants:
            if variant.url == parent.url and variant.quality == "Source":
                continue
            media = parent.model_copy(
                update={
                    "url": variant.url,
                    "name": f"{parent.name} - {variant.quality}",
                    "quality": variant.quality,
                }
            )
            self._add_media(media)

    def _start_download(self, media: BrowserMedia) -> None:
        destination = Path(self.destination.text()).expanduser()
        task_id = self.manager.start(media, destination)
        row = self.download_table.rowCount()
        self.download_table.insertRow(row)
        self.download_rows[task_id] = row
        for column, value in enumerate((media.name, "⏳ queued", "0%", "-", "-", "-", "")):
            self.download_table.setItem(row, column, QTableWidgetItem(value))
        controls = QWidget()
        controls_layout = QHBoxLayout(controls)
        controls_layout.setContentsMargins(2, 0, 2, 0)
        controls_layout.setSpacing(4)
        for label, tooltip, callback in (
            ("⏸", "Pause", lambda: self.manager.pause(task_id)),
            ("▶", "Resume", lambda: self.manager.resume(task_id)),
            ("✖", "Cancel", lambda: self.manager.cancel(task_id)),
        ):
            button = QPushButton(label)
            button.setToolTip(tooltip)
            button.setProperty("cssClass", "secondary")
            button.setFixedSize(28, 24)
            button.clicked.connect(callback)
            controls_layout.addWidget(button)
        self.download_table.setCellWidget(row, 6, controls)

    @Slot(object)
    def _update_download(self, snapshot: BrowserDownloadSnapshot) -> None:
        row = self.download_rows.get(snapshot.task_id)
        if row is None:
            return

        state_icons = {
            DownloadState.QUEUED: "⏳",
            DownloadState.DOWNLOADING: "📥",
            DownloadState.PAUSED: "⏸",
            DownloadState.COMPLETED: "✅",
            DownloadState.CANCELLED: "🚫",
            DownloadState.FAILED: "❌",
        }
        icon = state_icons.get(snapshot.state, "")

        values = (
            snapshot.media.name,
            f"{icon} {snapshot.state.value}",
            f"{snapshot.percent:.1f}%",
            f"{format_bytes(snapshot.speed)}/s",
            f"{snapshot.eta or 0:.0f}s",
            str(snapshot.output_path or ""),
        )
        for column, value in enumerate(values):
            self.download_table.setItem(row, column, QTableWidgetItem(value))

        if snapshot.state is DownloadState.COMPLETED and snapshot.output_path:
            item = self.download_table.item(row, 5)
            item.setToolTip(str(snapshot.output_path))
            self._offer_save_as(snapshot)

    def _offer_save_as(self, snapshot: BrowserDownloadSnapshot) -> None:
        """Open a Save As dialog after a download completes."""
        src = snapshot.output_path
        if not src or not src.exists():
            return

        save_path, _ = QFileDialog.getSaveFileName(
            self,
            f"Save — {src.name}",
            str(Path.home() / src.name),
            f"Media file (*{src.suffix});;All files (*.*)",
        )
        if save_path:
            dest = Path(save_path)
            if dest != src:
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(src), str(dest))
            # Update the file column with new path
            row = self.download_rows.get(snapshot.task_id)
            if row is not None:
                self.download_table.setItem(
                    row, 5, QTableWidgetItem(str(dest))
                )

            # Replace controls with Open Folder button
            self._set_open_folder_button(snapshot.task_id, dest.parent)
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            self.file_saved.emit(snapshot.media.name, str(dest), timestamp)
        else:
            # User cancelled — add Open Folder for original location
            self._set_open_folder_button(snapshot.task_id, src.parent)
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            self.file_saved.emit(snapshot.media.name, str(src), timestamp)

    def _set_open_folder_button(self, task_id: str, folder: Path) -> None:
        """Replace download controls with an Open Folder button."""
        row = self.download_rows.get(task_id)
        if row is None:
            return
        btn = QPushButton("📂 Open")
        btn.setToolTip(str(folder))
        btn.setProperty("cssClass", "secondary")
        btn.clicked.connect(
            lambda _checked=False, p=folder: self._open_folder(p)
        )
        self.download_table.setCellWidget(row, 6, btn)

    @staticmethod
    def _open_folder(folder: Path) -> None:
        """Open folder in Windows File Explorer."""
        subprocess.Popen(["explorer", str(folder)])  # noqa: S603

    def _browse(self) -> None:
        selected = QFileDialog.getExistingDirectory(
            self, "Select download directory", self.destination.text()
        )
        if selected:
            self.destination.setText(selected)

    def _cookie_added(self, cookie) -> None:
        name = bytes(cookie.name()).decode("utf-8", errors="ignore")
        value = bytes(cookie.value()).decode("utf-8", errors="ignore")
        if name:
            self.cookies.add(
                BrowserCookie(
                    name=name,
                    value=value,
                    domain=cookie.domain(),
                    path=cookie.path() or "/",
                    secure=cookie.isSecure(),
                )
            )

    @Slot(str)
    def _show_error(self, message: str) -> None:
        QMessageBox.warning(self, "Browser Downloader", message)

    def open_download(self, path: Path) -> None:
        """Open a completed download using the operating system."""
        QDesktopServices.openUrl(QUrl.fromLocalFile(str(path)))
