"""Qt implementation of the existing URL downloader."""

# PySide signals are generated by Shiboken and are invisible to pylint.
# pylint: disable=no-member

from __future__ import annotations

import shutil
from datetime import datetime
from pathlib import Path

from PySide6.QtCore import QObject, QRunnable, QThreadPool, Signal, Slot
from PySide6.QtWidgets import (
    QComboBox,
    QFileDialog,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QProgressBar,
    QPushButton,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from app.config.settings import AppConfig
from app.core.exceptions import VideoDownloaderError
from app.models.download import DownloadProgress
from app.models.quality import Quality
from app.services.download_service import DownloadService
from app.utils.formatting import format_bytes, format_duration


class _WorkerSignals(QObject):
    completed = Signal(object)
    failed = Signal(str)
    progress = Signal(object)


class _DownloadWorker(QRunnable):
    def __init__(self, service: DownloadService, url: str, quality: Quality) -> None:
        super().__init__()
        self.service = service
        self.url = url
        self.quality = quality
        self.signals = _WorkerSignals()

    @Slot()
    def run(self) -> None:
        """Execute a download outside the GUI thread."""
        try:
            results = self.service.download(
                self.url,
                self.quality,
                progress_callback=self.signals.progress.emit,
            )
            self.signals.completed.emit(results)
        except (VideoDownloaderError, OSError, ValueError) as exc:
            self.signals.failed.emit(str(exc))


class _InfoWorker(QRunnable):
    def __init__(self, service: DownloadService, url: str) -> None:
        super().__init__()
        self.service = service
        self.url = url
        self.signals = _WorkerSignals()

    @Slot()
    def run(self) -> None:
        """Read metadata outside the GUI thread."""
        try:
            self.signals.completed.emit(self.service.get_info(self.url))
        except (VideoDownloaderError, OSError, ValueError) as exc:
            self.signals.failed.emit(str(exc))


class ClassicDownloaderTab(QWidget):
    """Classic URL downloader backed by the existing application service."""

    # Signal emitted when a file is saved: (title, saved_path, timestamp)
    file_saved = Signal(str, str, str)

    def __init__(self, config: AppConfig) -> None:
        super().__init__()
        self.config = config
        self.thread_pool = QThreadPool.globalInstance()
        self._build()

    def _build(self) -> None:
        layout = QVBoxLayout(self)
        layout.setSpacing(8)
        layout.setContentsMargins(10, 10, 10, 10)

        # ── Input Section ──
        form = QFormLayout()
        form.setSpacing(8)
        self.url_edit = QLineEdit()
        self.url_edit.setPlaceholderText("https://youtube.com/watch?v=...")
        form.addRow("🔗  Video URL", self.url_edit)

        self.quality_combo = QComboBox()
        self.quality_combo.addItems([quality.value for quality in Quality])
        self.quality_combo.setCurrentText(self.config.default_quality.value)
        form.addRow("📊  Quality", self.quality_combo)
        layout.addLayout(form)

        # ── Action Buttons ──
        button_row = QHBoxLayout()
        button_row.setSpacing(10)
        self.download_button = QPushButton("⬇  Download")
        self.download_button.clicked.connect(self._download)
        info_button = QPushButton("ℹ  Show Info")
        info_button.setProperty("cssClass", "secondary")
        info_button.clicked.connect(self._show_info)
        button_row.addWidget(self.download_button)
        button_row.addWidget(info_button)
        button_row.addStretch()
        layout.addLayout(button_row)

        # ── Compact Progress Section ──
        progress_group = QGroupBox()
        progress_group.setStyleSheet(
            "QGroupBox { "
            "  background: #121322; "
            "  border: 1px solid #1e2030; "
            "  border-radius: 8px; "
            "  padding: 8px; "
            "  margin-top: 2px; "
            "}"
        )
        progress_layout = QVBoxLayout(progress_group)
        progress_layout.setSpacing(4)
        progress_layout.setContentsMargins(8, 8, 8, 8)

        self.progress = QProgressBar()
        self.progress.setRange(0, 100)
        progress_layout.addWidget(self.progress)

        self.status = QLabel("Ready")
        self.status.setProperty("cssClass", "status")
        progress_layout.addWidget(self.status)
        layout.addWidget(progress_group)

        # ── Details / Info area ──
        self.details = QTextEdit()
        self.details.setReadOnly(True)
        self.details.setMaximumHeight(120)
        self.details.setPlaceholderText("Video information will appear here...")
        layout.addWidget(self.details, 1)

    def _service(self) -> DownloadService:
        return DownloadService(self.config)

    def _download(self) -> None:
        url = self.url_edit.text().strip()
        if not url:
            QMessageBox.warning(self, "Invalid URL", "Enter a video URL.")
            return
        self.download_button.setEnabled(False)
        self.progress.setValue(0)
        self.status.setText("⏳ Preparing download...")
        worker = _DownloadWorker(
            self._service(), url, Quality(self.quality_combo.currentText())
        )
        worker.signals.progress.connect(self._on_progress)
        worker.signals.completed.connect(self._download_complete)
        worker.signals.failed.connect(self._failed)
        self.thread_pool.start(worker)

    def _show_info(self) -> None:
        url = self.url_edit.text().strip()
        if not url:
            QMessageBox.warning(self, "Invalid URL", "Enter a video URL.")
            return
        self.status.setText("⏳ Reading metadata...")
        worker = _InfoWorker(self._service(), url)
        worker.signals.completed.connect(self._info_complete)
        worker.signals.failed.connect(self._failed)
        self.thread_pool.start(worker)

    @Slot(object)
    def _on_progress(self, event: DownloadProgress) -> None:
        self.progress.setValue(round(event.percent))
        self.status.setText(
            f"📥 {event.percent:.1f}%  •  {format_bytes(event.downloaded_bytes)}  •  "
            f"{format_bytes(event.speed)}/s  •  ETA {event.eta or 0:.0f}s"
        )

    @Slot(object)
    def _download_complete(self, results: object) -> None:
        self.download_button.setEnabled(True)
        self.progress.setValue(100)
        self.status.setText("✅ Download complete!")

        saved_paths = []
        for result in results:
            src = Path(result.path)
            title = getattr(result, "title", src.stem)
            if not src.exists():
                saved_paths.append(str(src))
                continue

            # Open native Save As dialog for each downloaded file
            save_path, _ = QFileDialog.getSaveFileName(
                self,
                f"Save video — {src.name}",
                str(Path.home() / src.name),
                f"Video file (*{src.suffix});;All files (*.*)",
            )
            if save_path:
                dest = Path(save_path)
                if dest != src:
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(src), str(dest))
                saved_paths.append(str(dest))
            else:
                # User cancelled — keep file at original location
                dest = src
                saved_paths.append(str(src))

            # Emit history signal
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            self.file_saved.emit(title, str(dest), timestamp)

        self.details.setPlainText("\n".join(saved_paths))

    @Slot(object)
    def _info_complete(self, items: object) -> None:
        lines = []
        for item in items:
            lines.append(
                f"{item.title}\nAuthor: {item.author or 'unknown'}\n"
                f"Duration: {format_duration(item.duration)}\n"
                f"Estimated size: {format_bytes(item.estimated_size)}"
            )
        self.details.setPlainText("\n\n".join(lines))
        self.status.setText("ℹ  Metadata loaded")

    @Slot(str)
    def _failed(self, message: str) -> None:
        self.download_button.setEnabled(True)
        self.status.setText(f"❌ {message}")
        QMessageBox.critical(self, "Operation failed", message)

