"""Qt implementation of the existing URL downloader."""

# PySide signals are generated by Shiboken and are invisible to pylint.
# pylint: disable=no-member

from __future__ import annotations

import shutil
from datetime import datetime
from pathlib import Path

from PySide6.QtCore import QObject, QRunnable, QThreadPool, Signal, Slot
from PySide6.QtWidgets import (
    QComboBox,
    QFileDialog,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QProgressBar,
    QPushButton,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from app.config.settings import AppConfig
from app.core.exceptions import PrivateVideoError, VideoDownloaderError
from app.gui.dialogs import BrowserRetryDialog
from app.gui.settings_tab import BROWSER_CHOICES
from app.models.download import DownloadProgress
from app.models.quality import Quality
from app.services.download_service import DownloadService
from app.utils import get_initial_save_dir, set_last_save_dir
from app.utils.formatting import format_bytes, format_duration

# Auth-related keywords that trigger the cookie-retry dialog
_AUTH_KEYWORDS = ("authentication", "login required", "sign in", "cookies_file")


class _WorkerSignals(QObject):
    completed = Signal(object)
    failed = Signal(str, bool)   # message, is_auth_error
    progress = Signal(object)


class _DownloadWorker(QRunnable):
    def __init__(
        self,
        service: DownloadService,
        url: str,
        quality: Quality,
        download_type: str = "video+audio",
        audio_format: str = "mp3",
    ) -> None:
        super().__init__()
        self.service = service
        self.url = url
        self.quality = quality
        self.download_type = download_type
        self.audio_format = audio_format
        self.signals = _WorkerSignals()

    @Slot()
    def run(self) -> None:
        """Execute a download outside the GUI thread."""
        try:
            results = self.service.download(
                self.url,
                self.quality,
                download_type=self.download_type,
                audio_format=self.audio_format,
                progress_callback=self.signals.progress.emit,
            )
            self.signals.completed.emit(results)
        except (VideoDownloaderError, OSError, ValueError) as exc:
            is_auth = isinstance(exc, PrivateVideoError)
            self.signals.failed.emit(str(exc), is_auth)


class _InfoWorker(QRunnable):
    def __init__(self, service: DownloadService, url: str) -> None:
        super().__init__()
        self.service = service
        self.url = url
        self.signals = _WorkerSignals()

    @Slot()
    def run(self) -> None:
        """Read metadata outside the GUI thread."""
        try:
            self.signals.completed.emit(self.service.get_info(self.url))
        except (VideoDownloaderError, OSError, ValueError) as exc:
            self.signals.failed.emit(str(exc), False)


class ClassicDownloaderTab(QWidget):
    """Classic URL downloader backed by the existing application service."""

    # Signal emitted when a file is saved: (title, saved_path, timestamp)
    file_saved = Signal(str, str, str)

    def __init__(self, config: AppConfig) -> None:
        super().__init__()
        self.config = config
        self.thread_pool = QThreadPool.globalInstance()
        self._build()

    def _build(self) -> None:
        layout = QVBoxLayout(self)
        layout.setSpacing(8)
        layout.setContentsMargins(10, 10, 10, 10)

        # ── Input Section ──
        form = QFormLayout()
        form.setSpacing(8)
        self.url_edit = QLineEdit()
        self.url_edit.setPlaceholderText("https://youtube.com/watch?v=...")
        form.addRow("🔗  Video URL", self.url_edit)

        self.quality_combo = QComboBox()
        self.quality_combo.addItems([quality.value for quality in Quality])
        self.quality_combo.setCurrentText(self.config.default_quality.value)
        form.addRow("📊  Quality", self.quality_combo)

        self.type_combo = QComboBox()
        self.type_combo.addItems(["Video + Audio", "Video Only", "Audio Only"])
        self.type_combo.setCurrentIndex(0)
        self.type_combo.currentIndexChanged.connect(self._on_type_changed)
        form.addRow("📦  Download Type", self.type_combo)

        self.audio_format_label = QLabel("🎵  Audio Format")
        self.audio_format_combo = QComboBox()
        self.audio_format_combo.addItems(["mp3", "wav", "ogg"])
        self.audio_format_combo.setCurrentText("mp3")
        self.audio_format_label.setVisible(False)
        self.audio_format_combo.setVisible(False)
        form.addRow(self.audio_format_label, self.audio_format_combo)

        layout.addLayout(form)

        # ── Action Buttons ──
        button_row = QHBoxLayout()
        button_row.setSpacing(10)
        self.download_button = QPushButton("⬇  Download")
        self.download_button.clicked.connect(self._download)
        info_button = QPushButton("ℹ  Show Info")
        info_button.setProperty("cssClass", "secondary")
        info_button.clicked.connect(self._show_info)
        button_row.addWidget(self.download_button)
        button_row.addWidget(info_button)
        button_row.addStretch()
        layout.addLayout(button_row)

        # ── Compact Progress Section ──
        progress_group = QGroupBox()
        progress_group.setStyleSheet(
            "QGroupBox { "
            "  background: #121322; "
            "  border: 1px solid #1e2030; "
            "  border-radius: 8px; "
            "  padding: 8px; "
            "  margin-top: 2px; "
            "}"
        )
        progress_layout = QVBoxLayout(progress_group)
        progress_layout.setSpacing(4)
        progress_layout.setContentsMargins(8, 8, 8, 8)

        self.progress = QProgressBar()
        self.progress.setRange(0, 100)
        progress_layout.addWidget(self.progress)

        status_layout = QHBoxLayout()
        self.status = QLabel("Ready")
        self.status.setProperty("cssClass", "status")
        status_layout.addWidget(self.status)

        status_layout.addStretch()

        self.downloading_label = QLabel("Đang tải...")
        self.downloading_label.setStyleSheet("color: #22C55E; font-weight: bold;")
        self.downloading_label.setVisible(False)
        status_layout.addWidget(self.downloading_label)

        progress_layout.addLayout(status_layout)
        layout.addWidget(progress_group)

        # ── Details / Info area ──
        self.details = QTextEdit()
        self.details.setReadOnly(True)
        self.details.setMaximumHeight(120)
        self.details.setPlaceholderText("Video information will appear here...")
        layout.addWidget(self.details, 1)

    def _service(self) -> DownloadService:
        return DownloadService(self.config)

    def _download(self) -> None:
        url = self.url_edit.text().strip()
        if not url:
            QMessageBox.warning(self, "Invalid URL", "Enter a video URL.")
            return
        self.download_button.setEnabled(False)
        self.progress.setValue(0)
        self.status.setText("⏳ Preparing download...")
        self.downloading_label.setVisible(True)
        download_types = ["video+audio", "video", "audio"]
        dtype = download_types[self.type_combo.currentIndex()]
        audio_format = self.audio_format_combo.currentText()
        worker = _DownloadWorker(
            self._service(),
            url,
            Quality(self.quality_combo.currentText()),
            download_type=dtype,
            audio_format=audio_format,
        )
        worker.signals.progress.connect(self._on_progress)
        worker.signals.completed.connect(self._download_complete)
        worker.signals.failed.connect(self._failed)
        self.thread_pool.start(worker)

    def _show_info(self) -> None:
        url = self.url_edit.text().strip()
        if not url:
            QMessageBox.warning(self, "Invalid URL", "Enter a video URL.")
            return
        self.status.setText("⏳ Reading metadata...")
        worker = _InfoWorker(self._service(), url)
        worker.signals.completed.connect(self._info_complete)
        worker.signals.failed.connect(self._failed)
        self.thread_pool.start(worker)

    @Slot(object)
    def _on_progress(self, event: DownloadProgress) -> None:
        self.progress.setValue(round(event.percent))
        self.status.setText(
            f"📥 {event.percent:.1f}%  •  {format_bytes(event.downloaded_bytes)}  •  "
            f"{format_bytes(event.speed)}/s  •  ETA {event.eta or 0:.0f}s"
        )

    @Slot(object)
    def _download_complete(self, results: object) -> None:
        self.downloading_label.setVisible(False)
        self.download_button.setEnabled(True)
        self.progress.setValue(100)
        self.status.setText("✅ Download complete!")

        saved_paths = []
        for result in results:
            src = Path(result.path)
            title = getattr(result, "title", src.stem)
            if not src.exists():
                saved_paths.append(str(src))
                continue

            # Open native Save As dialog for each downloaded file
            file_type_label = "audio" if src.suffix.lower() in [".mp3", ".wav", ".ogg", ".m4a"] else "video"
            initial_dir = get_initial_save_dir(self.config)
            save_path, _ = QFileDialog.getSaveFileName(
                self,
                f"Save {file_type_label} — {src.name}",
                str(initial_dir / src.name),
                f"{file_type_label.title()} file (*{src.suffix});;All files (*.*)",
            )
            if save_path:
                dest = Path(save_path)
                set_last_save_dir(dest)
                if dest != src:
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(src), str(dest))
                saved_paths.append(str(dest))
            else:
                # User cancelled — keep file at original location
                dest = src
                saved_paths.append(str(src))

            # Emit history signal
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            self.file_saved.emit(title, str(dest), timestamp)

        self.details.setPlainText("\n".join(saved_paths))

    @Slot(object)
    def _info_complete(self, items: object) -> None:
        lines = []
        for item in items:
            lines.append(
                f"{item.title}\nAuthor: {item.author or 'unknown'}\n"
                f"Duration: {format_duration(item.duration)}\n"
                f"Estimated size: {format_bytes(item.estimated_size)}"
            )
        self.details.setPlainText("\n\n".join(lines))
        self.status.setText("ℹ  Metadata loaded")

    @Slot(str, bool)
    def _failed(self, message: str, is_auth: bool = False) -> None:
        self.downloading_label.setVisible(False)
        self.download_button.setEnabled(True)

        clean_msg = message
        while clean_msg.startswith("ERROR: "):
            clean_msg = clean_msg[7:].strip()

        self.status.setText(f"❌ {clean_msg}")

        if is_auth and not self.config.cookies_from_browser:
            self._offer_browser_retry(clean_msg)
        else:
            QMessageBox.critical(self, "Operation failed", clean_msg)

    def _offer_browser_retry(self, original_message: str) -> None:
        """Show a dialog that lets the user retry instantly with browser cookies."""
        dialog = BrowserRetryDialog(self)
        if dialog.exec() == BrowserRetryDialog.DialogCode.Accepted:
            if dialog.selected_browser:
                self._retry_with_browser(dialog.selected_browser)
            elif dialog.open_settings:
                # Switch to settings tab so user can configure
                parent = self.parent()
                while parent and not hasattr(parent, "_tabs"):
                    parent = parent.parent()
                if parent:
                    settings_index = parent._tabs.indexOf(parent._settings)  # noqa: SLF001
                    parent._tabs.setCurrentIndex(settings_index)

    def _retry_with_browser(self, browser_key: str) -> None:
        """Re-run the download with cookies injected from the given browser."""
        url = self.url_edit.text().strip()
        if not url:
            return
        # Create a one-shot config copy with browser cookies enabled
        retry_config = self.config.model_copy(
            update={"cookies_from_browser": browser_key, "cookies_file": None}
        )
        self.download_button.setEnabled(False)
        self.progress.setValue(0)
        self.status.setText(f"⏳ Retrying with {browser_key.title()} cookies…")
        self.downloading_label.setVisible(True)

        download_types = ["video+audio", "video", "audio"]
        dtype = download_types[self.type_combo.currentIndex()]
        audio_format = self.audio_format_combo.currentText()
        worker = _DownloadWorker(
            DownloadService(retry_config),
            url,
            Quality(self.quality_combo.currentText()),
            download_type=dtype,
            audio_format=audio_format,
        )
        worker.signals.progress.connect(self._on_progress)
        worker.signals.completed.connect(self._download_complete)
        worker.signals.failed.connect(self._failed)
        self.thread_pool.start(worker)

    @Slot(int)
    def _on_type_changed(self, index: int) -> None:
        """Toggle the visibility of audio format options based on download type choice."""
        is_audio = index == 2
        self.audio_format_label.setVisible(is_audio)
        self.audio_format_combo.setVisible(is_audio)

